### PR TITLE
First time install

### PR DESCRIPTION
**Pull request by michaelachrisco**
Playing around with this repo. Added some very basic requirements and fixed some tab/print formatting in Py3

### CODE REVIEW

**Comment by matt-desmarais** [comment]
Thanks!
I have improved this project here is the assembly guide
https://www.mrdcreations.org/blog/2017/8/31/this-is-my-guide-on-how-to-make-the-base-model-of-piglass
If you want to see more features I have come up with go to my blog
https://www.mrdcreations.org/blog/
Features include:
YouTube streaming 
YouTube livestreaming
Bone conduction transducer

**Comment by michaelachrisco** [comment]
Thanks @matt-desmarais . @9Voltaire has a functional version of the piglass set up. The only issue now is the python script itself. when I run 
`python3 PiGlassBeta.py` it gives us a tabs vs spaces error. Just FYI in case this should be its own issue. Awesome library and setup!

**Comment by matt-desmarais** [comment]
I am fixing those errors now

**Comment by michaelachrisco** [comment]
Thanks man!

**Comment by matt-desmarais** [comment]
Should be fixed, I'm trying to install opencv for python3 and it's taking forever so I have not been able to test

**Comment by matt-desmarais** [comment]
I installed and tested opencv with python3.4 and I had to rewrite piglass program for python3 because numpy function getbuffer no longer exists in python 3
I will put python3 version in the repo
I put a wiki page up on how to install opencv for python3.4

**Pull request merged**
